/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_BUTTON_PERMISSION_BUTTON_PERMISSION_CODE_KEY
import cn.hubbo.dal.keys.T_BUTTON_PERMISSION_PK
import cn.hubbo.dal.tables.records.TButtonPermissionRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 按钮权限关联信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TButtonPermission(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TButtonPermissionRecord>?,
    parentPath: InverseForeignKey<out Record, TButtonPermissionRecord>?,
    aliased: Table<TButtonPermissionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TButtonPermissionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("按钮权限关联信息表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_button_permission</code>
         */
        val T_BUTTON_PERMISSION: TButtonPermission = TButtonPermission()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TButtonPermissionRecord> = TButtonPermissionRecord::class.java

    /**
     * The column <code>public.t_button_permission.id</code>. 按钮权限编号
     */
    val ID: TableField<TButtonPermissionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "按钮权限编号")

    /**
     * The column
     * <code>public.t_button_permission.button_permission_code</code>. 按钮权限字符
     */
    val BUTTON_PERMISSION_CODE: TableField<TButtonPermissionRecord, String?> = createField(DSL.name("button_permission_code"), SQLDataType.VARCHAR(255).nullable(false), this, "按钮权限字符")

    /**
     * The column <code>public.t_button_permission.button_name</code>. 按钮名称
     */
    val BUTTON_NAME: TableField<TButtonPermissionRecord, String?> = createField(DSL.name("button_name"), SQLDataType.VARCHAR(255).nullable(false), this, "按钮名称")

    /**
     * The column <code>public.t_button_permission.permission_id</code>. 权限编号
     */
    val PERMISSION_ID: TableField<TButtonPermissionRecord, Int?> = createField(DSL.name("permission_id"), SQLDataType.INTEGER.nullable(false), this, "权限编号")

    /**
     * The column <code>public.t_button_permission.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TButtonPermissionRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_button_permission.deleted</code>. 逻辑删除字段
     */
    val DELETED: TableField<TButtonPermissionRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "逻辑删除字段")

    /**
     * The column <code>public.t_button_permission.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TButtonPermissionRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_button_permission.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TButtonPermissionRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_button_permission.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TButtonPermissionRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_button_permission.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TButtonPermissionRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_button_permission.tenant_id</code>. 租户
     */
    val TENANT_ID: TableField<TButtonPermissionRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户")

    private constructor(alias: Name, aliased: Table<TButtonPermissionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TButtonPermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TButtonPermissionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_button_permission</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_button_permission</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_button_permission</code> table reference
     */
    constructor(): this(DSL.name("t_button_permission"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TButtonPermissionRecord> = T_BUTTON_PERMISSION_PK
    override fun getUniqueKeys(): List<UniqueKey<TButtonPermissionRecord>> = listOf(T_BUTTON_PERMISSION_BUTTON_PERMISSION_CODE_KEY)
    override fun `as`(alias: String): TButtonPermission = TButtonPermission(DSL.name(alias), this)
    override fun `as`(alias: Name): TButtonPermission = TButtonPermission(alias, this)
    override fun `as`(alias: Table<*>): TButtonPermission = TButtonPermission(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TButtonPermission = TButtonPermission(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TButtonPermission = TButtonPermission(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TButtonPermission = TButtonPermission(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TButtonPermission = TButtonPermission(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TButtonPermission = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TButtonPermission = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TButtonPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TButtonPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TButtonPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TButtonPermission = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TButtonPermission = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TButtonPermission = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TButtonPermission = where(DSL.notExists(select))
}
