/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_DICT_DATA_PK
import cn.hubbo.dal.tables.records.TDictDataRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 字典表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TDictData(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TDictDataRecord>?,
    parentPath: InverseForeignKey<out Record, TDictDataRecord>?,
    aliased: Table<TDictDataRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TDictDataRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("字典表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_dict_data</code>
         */
        val T_DICT_DATA: TDictData = TDictData()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TDictDataRecord> = TDictDataRecord::class.java

    /**
     * The column <code>public.t_dict_data.dict_id</code>. 字典编号
     */
    val DICT_ID: TableField<TDictDataRecord, Long?> = createField(DSL.name("dict_id"), SQLDataType.BIGINT.nullable(false), this, "字典编号")

    /**
     * The column <code>public.t_dict_data.dict_code</code>. 码值类型
     */
    val DICT_CODE: TableField<TDictDataRecord, String?> = createField(DSL.name("dict_code"), SQLDataType.VARCHAR(65).nullable(false), this, "码值类型")

    /**
     * The column <code>public.t_dict_data.code_value</code>. 码值
     */
    val CODE_VALUE: TableField<TDictDataRecord, String?> = createField(DSL.name("code_value"), SQLDataType.VARCHAR(255), this, "码值")

    /**
     * The column <code>public.t_dict_data.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TDictDataRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_dict_data.deleted</code>. 逻辑删除标志位
     */
    val DELETED: TableField<TDictDataRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "逻辑删除标志位")

    /**
     * The column <code>public.t_dict_data.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TDictDataRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_dict_data.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TDictDataRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_dict_data.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TDictDataRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_dict_data.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TDictDataRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_dict_data.description</code>. 备注信息
     */
    val DESCRIPTION: TableField<TDictDataRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "备注信息")

    /**
     * The column <code>public.t_dict_data.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TDictDataRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TDictDataRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TDictDataRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TDictDataRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_dict_data</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_dict_data</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_dict_data</code> table reference
     */
    constructor(): this(DSL.name("t_dict_data"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TDictDataRecord> = T_DICT_DATA_PK
    override fun `as`(alias: String): TDictData = TDictData(DSL.name(alias), this)
    override fun `as`(alias: Name): TDictData = TDictData(alias, this)
    override fun `as`(alias: Table<*>): TDictData = TDictData(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TDictData = TDictData(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TDictData = TDictData(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TDictData = TDictData(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TDictData = TDictData(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TDictData = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TDictData = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TDictData = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TDictData = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TDictData = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TDictData = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TDictData = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TDictData = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TDictData = where(DSL.notExists(select))
}
