/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_MENU_PERMISSION_PK
import cn.hubbo.dal.tables.records.TMenuPermissionRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 菜单权限关联表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TMenuPermission(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TMenuPermissionRecord>?,
    parentPath: InverseForeignKey<out Record, TMenuPermissionRecord>?,
    aliased: Table<TMenuPermissionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TMenuPermissionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("菜单权限关联表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_menu_permission</code>
         */
        val T_MENU_PERMISSION: TMenuPermission = TMenuPermission()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TMenuPermissionRecord> = TMenuPermissionRecord::class.java

    /**
     * The column <code>public.t_menu_permission.id</code>. 关系编号
     */
    val ID: TableField<TMenuPermissionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "关系编号")

    /**
     * The column <code>public.t_menu_permission.permission_id</code>. 权限编号
     */
    val PERMISSION_ID: TableField<TMenuPermissionRecord, Long?> = createField(DSL.name("permission_id"), SQLDataType.BIGINT.nullable(false), this, "权限编号")

    /**
     * The column <code>public.t_menu_permission.menu_id</code>. 菜单编号
     */
    val MENU_ID: TableField<TMenuPermissionRecord, Long?> = createField(DSL.name("menu_id"), SQLDataType.BIGINT.nullable(false), this, "菜单编号")

    /**
     * The column <code>public.t_menu_permission.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TMenuPermissionRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_menu_permission.deleted</code>. 是否删除
     */
    val DELETED: TableField<TMenuPermissionRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "是否删除")

    /**
     * The column <code>public.t_menu_permission.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TMenuPermissionRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_menu_permission.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TMenuPermissionRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_menu_permission.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TMenuPermissionRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_menu_permission.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TMenuPermissionRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_menu_permission.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TMenuPermissionRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TMenuPermissionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TMenuPermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TMenuPermissionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_menu_permission</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_menu_permission</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_menu_permission</code> table reference
     */
    constructor(): this(DSL.name("t_menu_permission"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TMenuPermissionRecord> = T_MENU_PERMISSION_PK
    override fun `as`(alias: String): TMenuPermission = TMenuPermission(DSL.name(alias), this)
    override fun `as`(alias: Name): TMenuPermission = TMenuPermission(alias, this)
    override fun `as`(alias: Table<*>): TMenuPermission = TMenuPermission(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TMenuPermission = TMenuPermission(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TMenuPermission = TMenuPermission(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TMenuPermission = TMenuPermission(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TMenuPermission = TMenuPermission(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TMenuPermission = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TMenuPermission = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TMenuPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TMenuPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TMenuPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TMenuPermission = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TMenuPermission = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TMenuPermission = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TMenuPermission = where(DSL.notExists(select))
}
