/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_MENU_PK
import cn.hubbo.dal.tables.records.TMenuRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 菜单配置信息表，对应前端的路由信息
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TMenu(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TMenuRecord>?,
    parentPath: InverseForeignKey<out Record, TMenuRecord>?,
    aliased: Table<TMenuRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TMenuRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("菜单配置信息表，对应前端的路由信息"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_menu</code>
         */
        val T_MENU: TMenu = TMenu()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TMenuRecord> = TMenuRecord::class.java

    /**
     * The column <code>public.t_menu.menu_id</code>. 菜单编号
     */
    val MENU_ID: TableField<TMenuRecord, Long?> = createField(DSL.name("menu_id"), SQLDataType.BIGINT.nullable(false), this, "菜单编号")

    /**
     * The column <code>public.t_menu.menu_name</code>. 菜单名
     */
    val MENU_NAME: TableField<TMenuRecord, String?> = createField(DSL.name("menu_name"), SQLDataType.VARCHAR(255).nullable(false), this, "菜单名")

    /**
     * The column <code>public.t_menu.path</code>. URI资源路径
     */
    val PATH: TableField<TMenuRecord, String?> = createField(DSL.name("path"), SQLDataType.VARCHAR(255).nullable(false), this, "URI资源路径")

    /**
     * The column <code>public.t_menu.component</code>. 渲染组件的路径
     */
    val COMPONENT: TableField<TMenuRecord, String?> = createField(DSL.name("component"), SQLDataType.VARCHAR(255).nullable(false), this, "渲染组件的路径")

    /**
     * The column <code>public.t_menu.level</code>. 菜单层级
     */
    val LEVEL: TableField<TMenuRecord, String?> = createField(DSL.name("level"), SQLDataType.CHAR(1).nullable(false), this, "菜单层级")

    /**
     * The column <code>public.t_menu.title</code>. 标题
     */
    val TITLE: TableField<TMenuRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(255), this, "标题")

    /**
     * The column <code>public.t_menu.icon</code>. 菜单icon
     */
    val ICON: TableField<TMenuRecord, String?> = createField(DSL.name("icon"), SQLDataType.VARCHAR(255), this, "菜单icon")

    /**
     * The column <code>public.t_menu.auth</code>. 是否需要认证
     */
    val AUTH: TableField<TMenuRecord, Boolean?> = createField(DSL.name("auth"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否需要认证")

    /**
     * The column <code>public.t_menu.keep_alive</code>. 是否缓存组件
     */
    val KEEP_ALIVE: TableField<TMenuRecord, Boolean?> = createField(DSL.name("keep_alive"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否缓存组件")

    /**
     * The column <code>public.t_menu.display_order</code>. 序号，查询结果根据此字段排序
     */
    val DISPLAY_ORDER: TableField<TMenuRecord, Int?> = createField(DSL.name("display_order"), SQLDataType.INTEGER, this, "序号，查询结果根据此字段排序")

    /**
     * The column <code>public.t_menu.menu_type</code>.  菜单类型，如目录C，菜单M，超链接L 
     */
    val MENU_TYPE: TableField<TMenuRecord, String?> = createField(DSL.name("menu_type"), SQLDataType.CHAR(1).defaultValue(DSL.field(DSL.raw("'M'::bpchar"), SQLDataType.CHAR)), this, " 菜单类型，如目录C，菜单M，超链接L ")

    /**
     * The column <code>public.t_menu.link</code>. 链接的地址，当menu_type为L时，此字段值有意义
     */
    val LINK: TableField<TMenuRecord, String?> = createField(DSL.name("link"), SQLDataType.VARCHAR(255), this, "链接的地址，当menu_type为L时，此字段值有意义")

    /**
     * The column <code>public.t_menu.upper_menu_id</code>. 父级菜单编号
     */
    val UPPER_MENU_ID: TableField<TMenuRecord, Long?> = createField(DSL.name("upper_menu_id"), SQLDataType.BIGINT, this, "父级菜单编号")

    /**
     * The column <code>public.t_menu.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TMenuRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_menu.deleted</code>. 逻辑删除字段
     */
    val DELETED: TableField<TMenuRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "逻辑删除字段")

    /**
     * The column <code>public.t_menu.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TMenuRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_menu.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TMenuRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_menu.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TMenuRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_menu.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TMenuRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_menu.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TMenuRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TMenuRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TMenuRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TMenuRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_menu</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_menu</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_menu</code> table reference
     */
    constructor(): this(DSL.name("t_menu"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TMenuRecord> = T_MENU_PK
    override fun getChecks(): List<Check<TMenuRecord>> = listOf(
        Internal.createCheck(this, DSL.name("t_menu_menu_type_check"), "((menu_type = ANY (ARRAY['C'::bpchar, 'M'::bpchar, 'L'::bpchar])))", true)
    )
    override fun `as`(alias: String): TMenu = TMenu(DSL.name(alias), this)
    override fun `as`(alias: Name): TMenu = TMenu(alias, this)
    override fun `as`(alias: Table<*>): TMenu = TMenu(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TMenu = TMenu(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TMenu = TMenu(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TMenu = TMenu(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TMenu = TMenu(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TMenu = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TMenu = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TMenu = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TMenu = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TMenu = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TMenu = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TMenu = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TMenu = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TMenu = where(DSL.notExists(select))
}
