/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_PERMISSION_PERMISSION_CODE_KEY
import cn.hubbo.dal.keys.T_PERMISSION_PK
import cn.hubbo.dal.tables.records.TPermissionRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 权限信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TPermission(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TPermissionRecord>?,
    parentPath: InverseForeignKey<out Record, TPermissionRecord>?,
    aliased: Table<TPermissionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TPermissionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("权限信息表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_permission</code>
         */
        val T_PERMISSION: TPermission = TPermission()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TPermissionRecord> = TPermissionRecord::class.java

    /**
     * The column <code>public.t_permission.permission_id</code>. 权限id
     */
    val PERMISSION_ID: TableField<TPermissionRecord, Long?> = createField(DSL.name("permission_id"), SQLDataType.BIGINT.nullable(false), this, "权限id")

    /**
     * The column <code>public.t_permission.permission_code</code>.
     * 权限字符串，三段式，module.menu.action,module模块，如system，auth，menu可以是一级菜单也可以是二级三级菜单，action即要执行的动作
     */
    val PERMISSION_CODE: TableField<TPermissionRecord, String?> = createField(DSL.name("permission_code"), SQLDataType.VARCHAR(255).nullable(false), this, "权限字符串，三段式，module.menu.action,module模块，如system，auth，menu可以是一级菜单也可以是二级三级菜单，action即要执行的动作")

    /**
     * The column <code>public.t_permission.permission_name</code>. 权限名称
     */
    val PERMISSION_NAME: TableField<TPermissionRecord, String?> = createField(DSL.name("permission_name"), SQLDataType.VARCHAR(255).nullable(false), this, "权限名称")

    /**
     * The column <code>public.t_permission.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TPermissionRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_permission.deleted</code>. 逻辑删除字段
     */
    val DELETED: TableField<TPermissionRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "逻辑删除字段")

    /**
     * The column <code>public.t_permission.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TPermissionRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_permission.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TPermissionRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_permission.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TPermissionRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_permission.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TPermissionRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_permission.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TPermissionRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TPermissionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TPermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TPermissionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_permission</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_permission</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_permission</code> table reference
     */
    constructor(): this(DSL.name("t_permission"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TPermissionRecord> = T_PERMISSION_PK
    override fun getUniqueKeys(): List<UniqueKey<TPermissionRecord>> = listOf(T_PERMISSION_PERMISSION_CODE_KEY)
    override fun `as`(alias: String): TPermission = TPermission(DSL.name(alias), this)
    override fun `as`(alias: Name): TPermission = TPermission(alias, this)
    override fun `as`(alias: Table<*>): TPermission = TPermission(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TPermission = TPermission(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TPermission = TPermission(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TPermission = TPermission(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TPermission = TPermission(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TPermission = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TPermission = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TPermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TPermission = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TPermission = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TPermission = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TPermission = where(DSL.notExists(select))
}
