/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_PROJECT_ITERATION_PKEY
import cn.hubbo.dal.tables.records.TProjectIterationRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 项目迭代记录表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TProjectIteration(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TProjectIterationRecord>?,
    parentPath: InverseForeignKey<out Record, TProjectIterationRecord>?,
    aliased: Table<TProjectIterationRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TProjectIterationRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("项目迭代记录表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_project_iteration</code>
         */
        val T_PROJECT_ITERATION: TProjectIteration = TProjectIteration()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TProjectIterationRecord> = TProjectIterationRecord::class.java

    /**
     * The column <code>public.t_project_iteration.iteration_id</code>. 迭代编号
     */
    val ITERATION_ID: TableField<TProjectIterationRecord, Long?> = createField(DSL.name("iteration_id"), SQLDataType.BIGINT.nullable(false), this, "迭代编号")

    /**
     * The column <code>public.t_project_iteration.project_id</code>. 项目编号
     */
    val PROJECT_ID: TableField<TProjectIterationRecord, Long?> = createField(DSL.name("project_id"), SQLDataType.BIGINT.nullable(false), this, "项目编号")

    /**
     * The column <code>public.t_project_iteration.iteration_name</code>. 迭代名称
     */
    val ITERATION_NAME: TableField<TProjectIterationRecord, String?> = createField(DSL.name("iteration_name"), SQLDataType.VARCHAR(255).nullable(false), this, "迭代名称")

    /**
     * The column <code>public.t_project_iteration.base_line</code>. 基线
     */
    val BASE_LINE: TableField<TProjectIterationRecord, String?> = createField(DSL.name("base_line"), SQLDataType.VARCHAR(64).nullable(false), this, "基线")

    /**
     * The column <code>public.t_project_iteration.current_branch</code>. 当前分支名称
     */
    val CURRENT_BRANCH: TableField<TProjectIterationRecord, String?> = createField(DSL.name("current_branch"), SQLDataType.VARCHAR(64).nullable(false), this, "当前分支名称")

    /**
     * The column <code>public.t_project_iteration.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TProjectIterationRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_project_iteration.deleted</code>. 是否删除
     */
    val DELETED: TableField<TProjectIterationRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "是否删除")

    /**
     * The column <code>public.t_project_iteration.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TProjectIterationRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_project_iteration.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TProjectIterationRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_project_iteration.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TProjectIterationRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_project_iteration.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TProjectIterationRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    private constructor(alias: Name, aliased: Table<TProjectIterationRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TProjectIterationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TProjectIterationRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_project_iteration</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_project_iteration</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_project_iteration</code> table reference
     */
    constructor(): this(DSL.name("t_project_iteration"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TProjectIterationRecord> = T_PROJECT_ITERATION_PKEY
    override fun `as`(alias: String): TProjectIteration = TProjectIteration(DSL.name(alias), this)
    override fun `as`(alias: Name): TProjectIteration = TProjectIteration(alias, this)
    override fun `as`(alias: Table<*>): TProjectIteration = TProjectIteration(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TProjectIteration = TProjectIteration(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TProjectIteration = TProjectIteration(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TProjectIteration = TProjectIteration(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TProjectIteration = TProjectIteration(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TProjectIteration = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TProjectIteration = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TProjectIteration = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TProjectIteration = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TProjectIteration = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TProjectIteration = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TProjectIteration = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TProjectIteration = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TProjectIteration = where(DSL.notExists(select))
}
