/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_PROJECT_PKEY
import cn.hubbo.dal.keys.T_PROJECT_PROJECT_NAME_KEY
import cn.hubbo.dal.tables.records.TProjectRecord

import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 项目信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TProject(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TProjectRecord>?,
    parentPath: InverseForeignKey<out Record, TProjectRecord>?,
    aliased: Table<TProjectRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TProjectRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("项目信息表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_project</code>
         */
        val T_PROJECT: TProject = TProject()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TProjectRecord> = TProjectRecord::class.java

    /**
     * The column <code>public.t_project.project_id</code>. 项目编号
     */
    val PROJECT_ID: TableField<TProjectRecord, Long?> = createField(DSL.name("project_id"), SQLDataType.BIGINT.nullable(false), this, "项目编号")

    /**
     * The column <code>public.t_project.project_name</code>. 项目名称
     */
    val PROJECT_NAME: TableField<TProjectRecord, String?> = createField(DSL.name("project_name"), SQLDataType.VARCHAR(255).nullable(false), this, "项目名称")

    /**
     * The column <code>public.t_project.project_owner</code>.
     * 项目管理人，超管，具体的授权后续设计
     */
    val PROJECT_OWNER: TableField<TProjectRecord, Long?> = createField(DSL.name("project_owner"), SQLDataType.BIGINT.nullable(false), this, "项目管理人，超管，具体的授权后续设计")

    /**
     * The column <code>public.t_project.repository_url</code>. 仓库地址
     */
    val REPOSITORY_URL: TableField<TProjectRecord, String?> = createField(DSL.name("repository_url"), SQLDataType.VARCHAR(255).nullable(false), this, "仓库地址")

    /**
     * The column <code>public.t_project.master_branch</code>. 主分支
     */
    val MASTER_BRANCH: TableField<TProjectRecord, String?> = createField(DSL.name("master_branch"), SQLDataType.VARCHAR(255).nullable(false), this, "主分支")

    /**
     * The column <code>public.t_project.build_type</code>.
     * 构建类型，maven、gradle、npm、pnpm、rsBuild
     */
    val BUILD_TYPE: TableField<TProjectRecord, String?> = createField(DSL.name("build_type"), SQLDataType.CHAR(1).nullable(false), this, "构建类型，maven、gradle、npm、pnpm、rsBuild")

    /**
     * The column <code>public.t_project.build_config_id</code>. 构建配置的关联id
     */
    val BUILD_CONFIG_ID: TableField<TProjectRecord, Long?> = createField(DSL.name("build_config_id"), SQLDataType.BIGINT.nullable(false), this, "构建配置的关联id")

    /**
     * The column <code>public.t_project.current_branch</code>. 当前的正式分支
     */
    val CURRENT_BRANCH: TableField<TProjectRecord, String?> = createField(DSL.name("current_branch"), SQLDataType.VARCHAR(255).nullable(false), this, "当前的正式分支")

    /**
     * The column <code>public.t_project.publish_mode</code>. 发布模式，支持
     * full全量发布、group分组发布...
     */
    val PUBLISH_MODE: TableField<TProjectRecord, String?> = createField(DSL.name("publish_mode"), SQLDataType.CHAR(1).nullable(false), this, "发布模式，支持 full全量发布、group分组发布...")

    private constructor(alias: Name, aliased: Table<TProjectRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TProjectRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TProjectRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_project</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_project</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_project</code> table reference
     */
    constructor(): this(DSL.name("t_project"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TProjectRecord> = T_PROJECT_PKEY
    override fun getUniqueKeys(): List<UniqueKey<TProjectRecord>> = listOf(T_PROJECT_PROJECT_NAME_KEY)
    override fun `as`(alias: String): TProject = TProject(DSL.name(alias), this)
    override fun `as`(alias: Name): TProject = TProject(alias, this)
    override fun `as`(alias: Table<*>): TProject = TProject(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TProject = TProject(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TProject = TProject(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TProject = TProject(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TProject = TProject(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TProject = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TProject = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TProject = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TProject = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TProject = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TProject = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TProject = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TProject = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TProject = where(DSL.notExists(select))
}
