/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_ROLE_PK
import cn.hubbo.dal.tables.records.TRoleRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 角色基础信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TRole(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TRoleRecord>?,
    parentPath: InverseForeignKey<out Record, TRoleRecord>?,
    aliased: Table<TRoleRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TRoleRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("角色基础信息表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_role</code>
         */
        val T_ROLE: TRole = TRole()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TRoleRecord> = TRoleRecord::class.java

    /**
     * The column <code>public.t_role.role_id</code>. 角色id
     */
    val ROLE_ID: TableField<TRoleRecord, Long?> = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "角色id")

    /**
     * The column <code>public.t_role.role_name</code>. 角色名称
     */
    val ROLE_NAME: TableField<TRoleRecord, String?> = createField(DSL.name("role_name"), SQLDataType.VARCHAR(255).nullable(false), this, "角色名称")

    /**
     * The column <code>public.t_role.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TRoleRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_role.deleted</code>. 逻辑删除字段
     */
    val DELETED: TableField<TRoleRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "逻辑删除字段")

    /**
     * The column <code>public.t_role.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TRoleRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_role.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TRoleRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_role.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TRoleRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_role.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TRoleRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_role.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TRoleRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TRoleRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TRoleRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TRoleRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_role</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_role</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_role</code> table reference
     */
    constructor(): this(DSL.name("t_role"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TRoleRecord> = T_ROLE_PK
    override fun `as`(alias: String): TRole = TRole(DSL.name(alias), this)
    override fun `as`(alias: Name): TRole = TRole(alias, this)
    override fun `as`(alias: Table<*>): TRole = TRole(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TRole = TRole(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TRole = TRole(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TRole = TRole(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TRole = TRole(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TRole = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TRole = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TRole = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TRole = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TRole = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TRole = where(DSL.notExists(select))
}
