/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_ROLE_PERMISSION_PK
import cn.hubbo.dal.keys.T_ROLE_PERMISSION_UK
import cn.hubbo.dal.tables.records.TRolePermissionRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 角色权限关联信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TRolePermission(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TRolePermissionRecord>?,
    parentPath: InverseForeignKey<out Record, TRolePermissionRecord>?,
    aliased: Table<TRolePermissionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TRolePermissionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("角色权限关联信息表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_role_permission</code>
         */
        val T_ROLE_PERMISSION: TRolePermission = TRolePermission()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TRolePermissionRecord> = TRolePermissionRecord::class.java

    /**
     * The column <code>public.t_role_permission.id</code>. 主键编号
     */
    val ID: TableField<TRolePermissionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键编号")

    /**
     * The column <code>public.t_role_permission.role_id</code>. 角色id
     */
    val ROLE_ID: TableField<TRolePermissionRecord, Long?> = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "角色id")

    /**
     * The column <code>public.t_role_permission.permission_id</code>. 权限编号
     */
    val PERMISSION_ID: TableField<TRolePermissionRecord, Long?> = createField(DSL.name("permission_id"), SQLDataType.BIGINT.nullable(false), this, "权限编号")

    /**
     * The column <code>public.t_role_permission.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TRolePermissionRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_role_permission.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TRolePermissionRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_role_permission.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TRolePermissionRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_role_permission.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TRolePermissionRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_role_permission.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TRolePermissionRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_role_permission.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TRolePermissionRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TRolePermissionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TRolePermissionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TRolePermissionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_role_permission</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_role_permission</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_role_permission</code> table reference
     */
    constructor(): this(DSL.name("t_role_permission"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TRolePermissionRecord> = T_ROLE_PERMISSION_PK
    override fun getUniqueKeys(): List<UniqueKey<TRolePermissionRecord>> = listOf(T_ROLE_PERMISSION_UK)
    override fun `as`(alias: String): TRolePermission = TRolePermission(DSL.name(alias), this)
    override fun `as`(alias: Name): TRolePermission = TRolePermission(alias, this)
    override fun `as`(alias: Table<*>): TRolePermission = TRolePermission(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TRolePermission = TRolePermission(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TRolePermission = TRolePermission(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TRolePermission = TRolePermission(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TRolePermission = TRolePermission(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TRolePermission = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TRolePermission = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TRolePermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TRolePermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TRolePermission = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TRolePermission = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TRolePermission = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TRolePermission = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TRolePermission = where(DSL.notExists(select))
}
