/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_USER_PHONE_KEY
import cn.hubbo.dal.keys.T_USER_PK
import cn.hubbo.dal.tables.records.TUserRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 用户基础信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TUser(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TUserRecord>?,
    parentPath: InverseForeignKey<out Record, TUserRecord>?,
    aliased: Table<TUserRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TUserRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("用户基础信息表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_user</code>
         */
        val T_USER: TUser = TUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TUserRecord> = TUserRecord::class.java

    /**
     * The column <code>public.t_user.user_id</code>. 用户编号，分布式id
     */
    val USER_ID: TableField<TUserRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户编号，分布式id")

    /**
     * The column <code>public.t_user.user_name</code>. 用户名
     */
    val USER_NAME: TableField<TUserRecord, String?> = createField(DSL.name("user_name"), SQLDataType.VARCHAR(100).nullable(false), this, "用户名")

    /**
     * The column <code>public.t_user.phone</code>. 手机号
     */
    val PHONE: TableField<TUserRecord, String?> = createField(DSL.name("phone"), SQLDataType.CHAR(11).nullable(false), this, "手机号")

    /**
     * The column <code>public.t_user.passwd</code>. 用户密码，不要存储明文
     */
    val PASSWD: TableField<TUserRecord, String?> = createField(DSL.name("passwd"), SQLDataType.VARCHAR(100), this, "用户密码，不要存储明文")

    /**
     * The column <code>public.t_user.profile_url</code>. 头像url地址
     */
    val PROFILE_URL: TableField<TUserRecord, String?> = createField(DSL.name("profile_url"), SQLDataType.VARCHAR(255), this, "头像url地址")

    /**
     * The column <code>public.t_user.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TUserRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_user.deleted</code>. 逻辑删除字段
     */
    val DELETED: TableField<TUserRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "逻辑删除字段")

    /**
     * The column <code>public.t_user.create_by</code>. 创建人，用户自行注册的话值就是自己的id
     */
    val CREATE_BY: TableField<TUserRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人，用户自行注册的话值就是自己的id")

    /**
     * The column <code>public.t_user.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TUserRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_user.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TUserRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_user.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TUserRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_user.recent_online_time</code>. 最近一次的上线时间
     */
    val RECENT_ONLINE_TIME: TableField<TUserRecord, LocalDateTime?> = createField(DSL.name("recent_online_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "最近一次的上线时间")

    /**
     * The column <code>public.t_user.description</code>. 对用户的备注信息
     */
    val DESCRIPTION: TableField<TUserRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "对用户的备注信息")

    /**
     * The column <code>public.t_user.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TUserRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TUserRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TUserRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_user</code> table reference
     */
    constructor(): this(DSL.name("t_user"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TUserRecord> = T_USER_PK
    override fun getUniqueKeys(): List<UniqueKey<TUserRecord>> = listOf(T_USER_PHONE_KEY)
    override fun `as`(alias: String): TUser = TUser(DSL.name(alias), this)
    override fun `as`(alias: Name): TUser = TUser(alias, this)
    override fun `as`(alias: Table<*>): TUser = TUser(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TUser = TUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TUser = TUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TUser = TUser(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TUser = TUser(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TUser = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TUser = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TUser = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TUser = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TUser = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TUser = where(DSL.notExists(select))
}
