/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables


import cn.hubbo.dal.Public
import cn.hubbo.dal.keys.T_USER_ROLE_PK
import cn.hubbo.dal.tables.records.TUserRoleRecord

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 用户角色关联信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TUserRole(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TUserRoleRecord>?,
    parentPath: InverseForeignKey<out Record, TUserRoleRecord>?,
    aliased: Table<TUserRoleRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TUserRoleRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("用户角色关联信息表"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.t_user_role</code>
         */
        val T_USER_ROLE: TUserRole = TUserRole()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TUserRoleRecord> = TUserRoleRecord::class.java

    /**
     * The column <code>public.t_user_role.id</code>. 主键
     */
    val ID: TableField<TUserRoleRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键")

    /**
     * The column <code>public.t_user_role.user_id</code>. 用户编号，t_user主键
     */
    val USER_ID: TableField<TUserRoleRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户编号，t_user主键")

    /**
     * The column <code>public.t_user_role.role_id</code>. 角色编号，t_role主键
     */
    val ROLE_ID: TableField<TUserRoleRecord, Long?> = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "角色编号，t_role主键")

    /**
     * The column <code>public.t_user_role.enabled</code>. 是否启用
     */
    val ENABLED: TableField<TUserRoleRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "是否启用")

    /**
     * The column <code>public.t_user_role.deleted</code>. 逻辑删除
     */
    val DELETED: TableField<TUserRoleRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "逻辑删除")

    /**
     * The column <code>public.t_user_role.create_by</code>. 创建人
     */
    val CREATE_BY: TableField<TUserRoleRecord, Long?> = createField(DSL.name("create_by"), SQLDataType.BIGINT.nullable(false), this, "创建人")

    /**
     * The column <code>public.t_user_role.create_time</code>. 创建时间
     */
    val CREATE_TIME: TableField<TUserRoleRecord, LocalDateTime?> = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间")

    /**
     * The column <code>public.t_user_role.update_by</code>. 更新人
     */
    val UPDATE_BY: TableField<TUserRoleRecord, Long?> = createField(DSL.name("update_by"), SQLDataType.BIGINT, this, "更新人")

    /**
     * The column <code>public.t_user_role.update_time</code>. 更新时间
     */
    val UPDATE_TIME: TableField<TUserRoleRecord, LocalDateTime?> = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间")

    /**
     * The column <code>public.t_user_role.description</code>. 备注描述信息
     */
    val DESCRIPTION: TableField<TUserRoleRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "备注描述信息")

    /**
     * The column <code>public.t_user_role.tenant_id</code>. 租户id
     */
    val TENANT_ID: TableField<TUserRoleRecord, Long?> = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false), this, "租户id")

    private constructor(alias: Name, aliased: Table<TUserRoleRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TUserRoleRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TUserRoleRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.t_user_role</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.t_user_role</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.t_user_role</code> table reference
     */
    constructor(): this(DSL.name("t_user_role"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TUserRoleRecord> = T_USER_ROLE_PK
    override fun `as`(alias: String): TUserRole = TUserRole(DSL.name(alias), this)
    override fun `as`(alias: Name): TUserRole = TUserRole(alias, this)
    override fun `as`(alias: Table<*>): TUserRole = TUserRole(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TUserRole = TUserRole(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TUserRole = TUserRole(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TUserRole = TUserRole(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TUserRole = TUserRole(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TUserRole = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TUserRole = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TUserRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TUserRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TUserRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TUserRole = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TUserRole = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TUserRole = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TUserRole = where(DSL.notExists(select))
}
