/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.pojos


import cn.hubbo.dal.tables.interfaces.ITMenu

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 菜单配置信息表，对应前端的路由信息
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
data class TMenu(
    @get:NotNull
    override val menuId: Long,
    @get:NotNull
    @get:Size(max = 255)
    override val menuName: String,
    @get:NotNull
    @get:Size(max = 255)
    override val path: String,
    @get:NotNull
    @get:Size(max = 255)
    override val component: String,
    @get:NotNull
    @get:Size(max = 1)
    override val level: String,
    @get:Size(max = 255)
    override val title: String? = null,
    @get:Size(max = 255)
    override val icon: String? = null,
    override val auth: Boolean? = null,
    override val keepAlive: Boolean? = null,
    override val displayOrder: Int? = null,
    @get:Size(max = 1)
    override val menuType: String? = null,
    @get:Size(max = 255)
    override val link: String? = null,
    override val upperMenuId: Long? = null,
    override val enabled: Boolean? = null,
    override val deleted: Boolean? = null,
    @get:NotNull
    override val createBy: Long,
    override val createTime: LocalDateTime? = null,
    override val updateBy: Long? = null,
    override val updateTime: LocalDateTime? = null,
    @get:NotNull
    override val tenantId: Long
): ITMenu {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: TMenu = other as TMenu
        if (this.menuId != o.menuId)
            return false
        if (this.menuName != o.menuName)
            return false
        if (this.path != o.path)
            return false
        if (this.component != o.component)
            return false
        if (this.level != o.level)
            return false
        if (this.title == null) {
            if (o.title != null)
                return false
        }
        else if (this.title != o.title)
            return false
        if (this.icon == null) {
            if (o.icon != null)
                return false
        }
        else if (this.icon != o.icon)
            return false
        if (this.auth == null) {
            if (o.auth != null)
                return false
        }
        else if (this.auth != o.auth)
            return false
        if (this.keepAlive == null) {
            if (o.keepAlive != null)
                return false
        }
        else if (this.keepAlive != o.keepAlive)
            return false
        if (this.displayOrder == null) {
            if (o.displayOrder != null)
                return false
        }
        else if (this.displayOrder != o.displayOrder)
            return false
        if (this.menuType == null) {
            if (o.menuType != null)
                return false
        }
        else if (this.menuType != o.menuType)
            return false
        if (this.link == null) {
            if (o.link != null)
                return false
        }
        else if (this.link != o.link)
            return false
        if (this.upperMenuId == null) {
            if (o.upperMenuId != null)
                return false
        }
        else if (this.upperMenuId != o.upperMenuId)
            return false
        if (this.enabled == null) {
            if (o.enabled != null)
                return false
        }
        else if (this.enabled != o.enabled)
            return false
        if (this.deleted == null) {
            if (o.deleted != null)
                return false
        }
        else if (this.deleted != o.deleted)
            return false
        if (this.createBy != o.createBy)
            return false
        if (this.createTime == null) {
            if (o.createTime != null)
                return false
        }
        else if (this.createTime != o.createTime)
            return false
        if (this.updateBy == null) {
            if (o.updateBy != null)
                return false
        }
        else if (this.updateBy != o.updateBy)
            return false
        if (this.updateTime == null) {
            if (o.updateTime != null)
                return false
        }
        else if (this.updateTime != o.updateTime)
            return false
        if (this.tenantId != o.tenantId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.menuId.hashCode()
        result = prime * result + this.menuName.hashCode()
        result = prime * result + this.path.hashCode()
        result = prime * result + this.component.hashCode()
        result = prime * result + this.level.hashCode()
        result = prime * result + (if (this.title == null) 0 else this.title.hashCode())
        result = prime * result + (if (this.icon == null) 0 else this.icon.hashCode())
        result = prime * result + (if (this.auth == null) 0 else this.auth.hashCode())
        result = prime * result + (if (this.keepAlive == null) 0 else this.keepAlive.hashCode())
        result = prime * result + (if (this.displayOrder == null) 0 else this.displayOrder.hashCode())
        result = prime * result + (if (this.menuType == null) 0 else this.menuType.hashCode())
        result = prime * result + (if (this.link == null) 0 else this.link.hashCode())
        result = prime * result + (if (this.upperMenuId == null) 0 else this.upperMenuId.hashCode())
        result = prime * result + (if (this.enabled == null) 0 else this.enabled.hashCode())
        result = prime * result + (if (this.deleted == null) 0 else this.deleted.hashCode())
        result = prime * result + this.createBy.hashCode()
        result = prime * result + (if (this.createTime == null) 0 else this.createTime.hashCode())
        result = prime * result + (if (this.updateBy == null) 0 else this.updateBy.hashCode())
        result = prime * result + (if (this.updateTime == null) 0 else this.updateTime.hashCode())
        result = prime * result + this.tenantId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("TMenu (")

        sb.append(menuId)
        sb.append(", ").append(menuName)
        sb.append(", ").append(path)
        sb.append(", ").append(component)
        sb.append(", ").append(level)
        sb.append(", ").append(title)
        sb.append(", ").append(icon)
        sb.append(", ").append(auth)
        sb.append(", ").append(keepAlive)
        sb.append(", ").append(displayOrder)
        sb.append(", ").append(menuType)
        sb.append(", ").append(link)
        sb.append(", ").append(upperMenuId)
        sb.append(", ").append(enabled)
        sb.append(", ").append(deleted)
        sb.append(", ").append(createBy)
        sb.append(", ").append(createTime)
        sb.append(", ").append(updateBy)
        sb.append(", ").append(updateTime)
        sb.append(", ").append(tenantId)

        sb.append(")")
        return sb.toString()
    }
}
