/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.pojos


import cn.hubbo.dal.tables.interfaces.ITProject

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import javax.annotation.processing.Generated


/**
 * 项目信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
data class TProject(
    @get:NotNull
    override val projectId: Long,
    @get:NotNull
    @get:Size(max = 255)
    override val projectName: String,
    @get:NotNull
    override val projectOwner: Long,
    @get:NotNull
    @get:Size(max = 255)
    override val repositoryUrl: String,
    @get:NotNull
    @get:Size(max = 255)
    override val masterBranch: String,
    @get:NotNull
    @get:Size(max = 1)
    override val buildType: String,
    @get:NotNull
    override val buildConfigId: Long,
    @get:NotNull
    @get:Size(max = 255)
    override val currentBranch: String,
    @get:NotNull
    @get:Size(max = 1)
    override val publishMode: String
): ITProject {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: TProject = other as TProject
        if (this.projectId != o.projectId)
            return false
        if (this.projectName != o.projectName)
            return false
        if (this.projectOwner != o.projectOwner)
            return false
        if (this.repositoryUrl != o.repositoryUrl)
            return false
        if (this.masterBranch != o.masterBranch)
            return false
        if (this.buildType != o.buildType)
            return false
        if (this.buildConfigId != o.buildConfigId)
            return false
        if (this.currentBranch != o.currentBranch)
            return false
        if (this.publishMode != o.publishMode)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.projectId.hashCode()
        result = prime * result + this.projectName.hashCode()
        result = prime * result + this.projectOwner.hashCode()
        result = prime * result + this.repositoryUrl.hashCode()
        result = prime * result + this.masterBranch.hashCode()
        result = prime * result + this.buildType.hashCode()
        result = prime * result + this.buildConfigId.hashCode()
        result = prime * result + this.currentBranch.hashCode()
        result = prime * result + this.publishMode.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("TProject (")

        sb.append(projectId)
        sb.append(", ").append(projectName)
        sb.append(", ").append(projectOwner)
        sb.append(", ").append(repositoryUrl)
        sb.append(", ").append(masterBranch)
        sb.append(", ").append(buildType)
        sb.append(", ").append(buildConfigId)
        sb.append(", ").append(currentBranch)
        sb.append(", ").append(publishMode)

        sb.append(")")
        return sb.toString()
    }
}
