/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.pojos


import cn.hubbo.dal.tables.interfaces.ITProjectIteration

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 项目迭代记录表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
data class TProjectIteration(
    @get:NotNull
    override val iterationId: Long,
    @get:NotNull
    override val projectId: Long,
    @get:NotNull
    @get:Size(max = 255)
    override val iterationName: String,
    @get:NotNull
    @get:Size(max = 64)
    override val baseLine: String,
    @get:NotNull
    @get:Size(max = 64)
    override val currentBranch: String,
    override val enabled: Boolean? = null,
    override val deleted: Boolean? = null,
    @get:NotNull
    override val createBy: Long,
    override val createTime: LocalDateTime? = null,
    override val updateBy: Long? = null,
    override val updateTime: LocalDateTime? = null
): ITProjectIteration {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: TProjectIteration = other as TProjectIteration
        if (this.iterationId != o.iterationId)
            return false
        if (this.projectId != o.projectId)
            return false
        if (this.iterationName != o.iterationName)
            return false
        if (this.baseLine != o.baseLine)
            return false
        if (this.currentBranch != o.currentBranch)
            return false
        if (this.enabled == null) {
            if (o.enabled != null)
                return false
        }
        else if (this.enabled != o.enabled)
            return false
        if (this.deleted == null) {
            if (o.deleted != null)
                return false
        }
        else if (this.deleted != o.deleted)
            return false
        if (this.createBy != o.createBy)
            return false
        if (this.createTime == null) {
            if (o.createTime != null)
                return false
        }
        else if (this.createTime != o.createTime)
            return false
        if (this.updateBy == null) {
            if (o.updateBy != null)
                return false
        }
        else if (this.updateBy != o.updateBy)
            return false
        if (this.updateTime == null) {
            if (o.updateTime != null)
                return false
        }
        else if (this.updateTime != o.updateTime)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.iterationId.hashCode()
        result = prime * result + this.projectId.hashCode()
        result = prime * result + this.iterationName.hashCode()
        result = prime * result + this.baseLine.hashCode()
        result = prime * result + this.currentBranch.hashCode()
        result = prime * result + (if (this.enabled == null) 0 else this.enabled.hashCode())
        result = prime * result + (if (this.deleted == null) 0 else this.deleted.hashCode())
        result = prime * result + this.createBy.hashCode()
        result = prime * result + (if (this.createTime == null) 0 else this.createTime.hashCode())
        result = prime * result + (if (this.updateBy == null) 0 else this.updateBy.hashCode())
        result = prime * result + (if (this.updateTime == null) 0 else this.updateTime.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("TProjectIteration (")

        sb.append(iterationId)
        sb.append(", ").append(projectId)
        sb.append(", ").append(iterationName)
        sb.append(", ").append(baseLine)
        sb.append(", ").append(currentBranch)
        sb.append(", ").append(enabled)
        sb.append(", ").append(deleted)
        sb.append(", ").append(createBy)
        sb.append(", ").append(createTime)
        sb.append(", ").append(updateBy)
        sb.append(", ").append(updateTime)

        sb.append(")")
        return sb.toString()
    }
}
