/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.pojos


import cn.hubbo.dal.tables.interfaces.ITUserRole

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 用户角色关联信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
data class TUserRole(
    @get:NotNull
    override val id: Long,
    @get:NotNull
    override val userId: Long,
    @get:NotNull
    override val roleId: Long,
    override val enabled: Boolean? = null,
    override val deleted: Boolean? = null,
    @get:NotNull
    override val createBy: Long,
    override val createTime: LocalDateTime? = null,
    override val updateBy: Long? = null,
    override val updateTime: LocalDateTime? = null,
    @get:Size(max = 255)
    override val description: String? = null,
    @get:NotNull
    override val tenantId: Long
): ITUserRole {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: TUserRole = other as TUserRole
        if (this.id != o.id)
            return false
        if (this.userId != o.userId)
            return false
        if (this.roleId != o.roleId)
            return false
        if (this.enabled == null) {
            if (o.enabled != null)
                return false
        }
        else if (this.enabled != o.enabled)
            return false
        if (this.deleted == null) {
            if (o.deleted != null)
                return false
        }
        else if (this.deleted != o.deleted)
            return false
        if (this.createBy != o.createBy)
            return false
        if (this.createTime == null) {
            if (o.createTime != null)
                return false
        }
        else if (this.createTime != o.createTime)
            return false
        if (this.updateBy == null) {
            if (o.updateBy != null)
                return false
        }
        else if (this.updateBy != o.updateBy)
            return false
        if (this.updateTime == null) {
            if (o.updateTime != null)
                return false
        }
        else if (this.updateTime != o.updateTime)
            return false
        if (this.description == null) {
            if (o.description != null)
                return false
        }
        else if (this.description != o.description)
            return false
        if (this.tenantId != o.tenantId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.userId.hashCode()
        result = prime * result + this.roleId.hashCode()
        result = prime * result + (if (this.enabled == null) 0 else this.enabled.hashCode())
        result = prime * result + (if (this.deleted == null) 0 else this.deleted.hashCode())
        result = prime * result + this.createBy.hashCode()
        result = prime * result + (if (this.createTime == null) 0 else this.createTime.hashCode())
        result = prime * result + (if (this.updateBy == null) 0 else this.updateBy.hashCode())
        result = prime * result + (if (this.updateTime == null) 0 else this.updateTime.hashCode())
        result = prime * result + (if (this.description == null) 0 else this.description.hashCode())
        result = prime * result + this.tenantId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("TUserRole (")

        sb.append(id)
        sb.append(", ").append(userId)
        sb.append(", ").append(roleId)
        sb.append(", ").append(enabled)
        sb.append(", ").append(deleted)
        sb.append(", ").append(createBy)
        sb.append(", ").append(createTime)
        sb.append(", ").append(updateBy)
        sb.append(", ").append(updateTime)
        sb.append(", ").append(description)
        sb.append(", ").append(tenantId)

        sb.append(")")
        return sb.toString()
    }
}
