package cn.hubbo.unit.utils

import cn.hubbo.utils.coding.JavaCodeUtils.Companion.createJavFile
import cn.hubbo.utils.coding.JavaCodeUtils.Companion.getMethodSpecBuilder
import cn.hubbo.utils.coding.JavaCodeUtils.Companion.getTypeSpecBuilder
import com.squareup.javapoet.*
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import java.io.File
import java.util.*
import javax.lang.model.element.Modifier

private val log: Logger = LoggerFactory.getLogger(JavaCodeUtilsUnitTest::class.java)

@Disabled
class JavaCodeUtilsUnitTest {

    @BeforeEach
    fun setUp() {
        log.info("开始生成源码 {}", Date())
    }

    @AfterEach
    fun tearDown() {
        log.info("生成源码结束 {}", Date())
    }

    @Test
    fun testGenerateJavaFile2LocalDisk() {
        val methodSpec = getMethodSpecBuilder("main")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.SYNCHRONIZED)
            .addAnnotation(
                AnnotationSpec.builder(SuppressWarnings::class.java)
                    .addMember("value", CodeBlock.builder().add("{\$S}", "all").build()).build()
            )
            .addException(Exception::class.java)
            .addParameter(ParameterSpec.builder(Array<String>::class.java, "args", Modifier.FINAL).build())
            .addStatement("\$T.out.println(\$S)", System::class.java, "hello java poet !!!")
            .addStatement("int times = 100")
            .beginControlFlow("for(int i =0; i< \$N;i ++)", "times")
            .addStatement("\$T.out.println(\$N)", System::class.java, "i")
            .endControlFlow()
            .build()
        val fieldSpec = FieldSpec.builder(Int::class.java, "flag", Modifier.PRIVATE, Modifier.VOLATILE).build()
        val annotationSpec = AnnotationSpec.builder(SuppressWarnings::class.java)
            .addMember("value", CodeBlock.builder().add("{\$S}", "all").build())
            .build()
        val constructorSpec = MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PRIVATE)
            .build()
        val typeSpec = getTypeSpecBuilder("Demo")
            .addAnnotation(annotationSpec)
            .addModifiers(Modifier.PUBLIC)
            .addField(fieldSpec)
            .addMethod(methodSpec)
            .addMethod(constructorSpec)
            .build()
        val javaFile = createJavFile(
            "cn.hubbo.apt.demo", typeSpec, "Generated By Hubbo-APT"
        )
        javaFile.writeTo(File("D:\\tmp\\cache"))
    }


}
