/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.interfaces


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 字典表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
interface ITDictData : Serializable {
    @get:NotNull
    val dictId: Long
    @get:NotNull
    @get:Size(max = 65)
    val dictCode: String
    @get:Size(max = 255)
    val codeValue: String?
    val enabled: Boolean?
    val deleted: Boolean?
    @get:NotNull
    val createBy: Long
    val createTime: LocalDateTime?
    val updateBy: Long?
    val updateTime: LocalDateTime?
    @get:Size(max = 255)
    val description: String?
    @get:NotNull
    val tenantId: Long
}
