/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.interfaces


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 菜单配置信息表，对应前端的路由信息
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
interface ITMenu : Serializable {
    @get:NotNull
    val menuId: Long
    @get:NotNull
    @get:Size(max = 255)
    val menuName: String
    @get:NotNull
    @get:Size(max = 255)
    val path: String
    @get:NotNull
    @get:Size(max = 255)
    val component: String
    @get:NotNull
    @get:Size(max = 1)
    val level: String
    @get:Size(max = 255)
    val title: String?
    @get:Size(max = 255)
    val icon: String?
    val auth: Boolean?
    val keepAlive: Boolean?
    val displayOrder: Int?
    @get:Size(max = 1)
    val menuType: String?
    @get:Size(max = 255)
    val link: String?
    val upperMenuId: Long?
    val enabled: Boolean?
    val deleted: Boolean?
    @get:NotNull
    val createBy: Long
    val createTime: LocalDateTime?
    val updateBy: Long?
    val updateTime: LocalDateTime?
    @get:NotNull
    val tenantId: Long
}
