/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.interfaces


import jakarta.validation.constraints.NotNull

import java.io.Serializable
import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 菜单权限关联表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
interface ITMenuPermission : Serializable {
    @get:NotNull
    val id: Long
    @get:NotNull
    val permissionId: Long
    @get:NotNull
    val menuId: Long
    val enabled: Boolean?
    val deleted: Boolean?
    @get:NotNull
    val createBy: Long
    val createTime: LocalDateTime?
    val updateBy: Long?
    val updateTime: LocalDateTime?
    @get:NotNull
    val tenantId: Long
}
