/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.interfaces


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable

import javax.annotation.processing.Generated


/**
 * 项目信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
interface ITProject : Serializable {
    @get:NotNull
    val projectId: Long
    @get:NotNull
    @get:Size(max = 255)
    val projectName: String
    @get:NotNull
    val projectOwner: Long
    @get:NotNull
    @get:Size(max = 255)
    val repositoryUrl: String
    @get:NotNull
    @get:Size(max = 255)
    val masterBranch: String
    @get:NotNull
    @get:Size(max = 1)
    val buildType: String
    @get:NotNull
    val buildConfigId: Long
    @get:NotNull
    @get:Size(max = 255)
    val currentBranch: String
    @get:NotNull
    @get:Size(max = 1)
    val publishMode: String
}
