/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.interfaces


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 项目迭代记录表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
interface ITProjectIteration : Serializable {
    @get:NotNull
    val iterationId: Long
    @get:NotNull
    val projectId: Long
    @get:NotNull
    @get:Size(max = 255)
    val iterationName: String
    @get:NotNull
    @get:Size(max = 64)
    val baseLine: String
    @get:NotNull
    @get:Size(max = 64)
    val currentBranch: String
    val enabled: Boolean?
    val deleted: Boolean?
    @get:NotNull
    val createBy: Long
    val createTime: LocalDateTime?
    val updateBy: Long?
    val updateTime: LocalDateTime?
}
