/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.interfaces


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.time.LocalDateTime

import javax.annotation.processing.Generated


/**
 * 用户基础信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
interface ITUser : Serializable {
    @get:NotNull
    val userId: Long
    @get:NotNull
    @get:Size(max = 100)
    val userName: String
    @get:NotNull
    @get:Size(max = 11)
    val phone: String
    @get:Size(max = 100)
    val passwd: String?
    @get:Size(max = 255)
    val profileUrl: String?
    val enabled: Boolean?
    val deleted: Boolean?
    @get:NotNull
    val createBy: Long
    val createTime: LocalDateTime?
    val updateBy: Long?
    val updateTime: LocalDateTime?
    val recentOnlineTime: LocalDateTime?
    @get:Size(max = 255)
    val description: String?
    @get:NotNull
    val tenantId: Long
}
