/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.records


import cn.hubbo.dal.tables.TButtonPermission
import cn.hubbo.dal.tables.interfaces.ITButtonPermission

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 按钮权限关联信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TButtonPermissionRecord private constructor() : UpdatableRecordImpl<TButtonPermissionRecord>(TButtonPermission.T_BUTTON_PERMISSION), ITButtonPermission {

    @get:NotNull
    open override var id: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    @get:NotNull
    @get:Size(max = 255)
    open override var buttonPermissionCode: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    @get:NotNull
    @get:Size(max = 255)
    open override var buttonName: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    @get:NotNull
    open override var permissionId: Int
        set(value): Unit = set(3, value)
        get(): Int = get(3) as Int

    open override var enabled: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    open override var deleted: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    @get:NotNull
    open override var createBy: Long
        set(value): Unit = set(6, value)
        get(): Long = get(6) as Long

    open override var createTime: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open override var updateBy: Long?
        set(value): Unit = set(8, value)
        get(): Long? = get(8) as Long?

    open override var updateTime: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    @get:NotNull
    open override var tenantId: Long
        set(value): Unit = set(10, value)
        get(): Long = get(10) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ITButtonPermission) {
        this.id = from.id
        this.buttonPermissionCode = from.buttonPermissionCode
        this.buttonName = from.buttonName
        this.permissionId = from.permissionId
        this.enabled = from.enabled
        this.deleted = from.deleted
        this.createBy = from.createBy
        this.createTime = from.createTime
        this.updateBy = from.updateBy
        this.updateTime = from.updateTime
        this.tenantId = from.tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TButtonPermissionRecord
     */
    constructor(id: Long, buttonPermissionCode: String, buttonName: String, permissionId: Int, enabled: Boolean? = null, deleted: Boolean? = null, createBy: Long, createTime: LocalDateTime? = null, updateBy: Long? = null, updateTime: LocalDateTime? = null, tenantId: Long): this() {
        this.id = id
        this.buttonPermissionCode = buttonPermissionCode
        this.buttonName = buttonName
        this.permissionId = permissionId
        this.enabled = enabled
        this.deleted = deleted
        this.createBy = createBy
        this.createTime = createTime
        this.updateBy = updateBy
        this.updateTime = updateTime
        this.tenantId = tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TButtonPermissionRecord
     */
    constructor(value: ITButtonPermission?): this() {
        if (value != null) {
            this.id = value.id
            this.buttonPermissionCode = value.buttonPermissionCode
            this.buttonName = value.buttonName
            this.permissionId = value.permissionId
            this.enabled = value.enabled
            this.deleted = value.deleted
            this.createBy = value.createBy
            this.createTime = value.createTime
            this.updateBy = value.updateBy
            this.updateTime = value.updateTime
            this.tenantId = value.tenantId
            resetTouchedOnNotNull()
        }
    }
}
