/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.records


import cn.hubbo.dal.tables.TMenuPermission
import cn.hubbo.dal.tables.interfaces.ITMenuPermission

import jakarta.validation.constraints.NotNull

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 菜单权限关联表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TMenuPermissionRecord private constructor() : UpdatableRecordImpl<TMenuPermissionRecord>(TMenuPermission.T_MENU_PERMISSION), ITMenuPermission {

    @get:NotNull
    open override var id: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    @get:NotNull
    open override var permissionId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    @get:NotNull
    open override var menuId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var enabled: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    open override var deleted: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    @get:NotNull
    open override var createBy: Long
        set(value): Unit = set(5, value)
        get(): Long = get(5) as Long

    open override var createTime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open override var updateBy: Long?
        set(value): Unit = set(7, value)
        get(): Long? = get(7) as Long?

    open override var updateTime: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    @get:NotNull
    open override var tenantId: Long
        set(value): Unit = set(9, value)
        get(): Long = get(9) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ITMenuPermission) {
        this.id = from.id
        this.permissionId = from.permissionId
        this.menuId = from.menuId
        this.enabled = from.enabled
        this.deleted = from.deleted
        this.createBy = from.createBy
        this.createTime = from.createTime
        this.updateBy = from.updateBy
        this.updateTime = from.updateTime
        this.tenantId = from.tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TMenuPermissionRecord
     */
    constructor(id: Long, permissionId: Long, menuId: Long, enabled: Boolean? = null, deleted: Boolean? = null, createBy: Long, createTime: LocalDateTime? = null, updateBy: Long? = null, updateTime: LocalDateTime? = null, tenantId: Long): this() {
        this.id = id
        this.permissionId = permissionId
        this.menuId = menuId
        this.enabled = enabled
        this.deleted = deleted
        this.createBy = createBy
        this.createTime = createTime
        this.updateBy = updateBy
        this.updateTime = updateTime
        this.tenantId = tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TMenuPermissionRecord
     */
    constructor(value: ITMenuPermission?): this() {
        if (value != null) {
            this.id = value.id
            this.permissionId = value.permissionId
            this.menuId = value.menuId
            this.enabled = value.enabled
            this.deleted = value.deleted
            this.createBy = value.createBy
            this.createTime = value.createTime
            this.updateBy = value.updateBy
            this.updateTime = value.updateTime
            this.tenantId = value.tenantId
            resetTouchedOnNotNull()
        }
    }
}
