/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.records


import cn.hubbo.dal.tables.TMenu
import cn.hubbo.dal.tables.interfaces.ITMenu

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 菜单配置信息表，对应前端的路由信息
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TMenuRecord private constructor() : UpdatableRecordImpl<TMenuRecord>(TMenu.T_MENU), ITMenu {

    @get:NotNull
    open override var menuId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    @get:NotNull
    @get:Size(max = 255)
    open override var menuName: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    @get:NotNull
    @get:Size(max = 255)
    open override var path: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    @get:NotNull
    @get:Size(max = 255)
    open override var component: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    @get:NotNull
    @get:Size(max = 1)
    open override var level: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    @get:Size(max = 255)
    open override var title: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    @get:Size(max = 255)
    open override var icon: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open override var auth: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open override var keepAlive: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    open override var displayOrder: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    @get:Size(max = 1)
    open override var menuType: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    @get:Size(max = 255)
    open override var link: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open override var upperMenuId: Long?
        set(value): Unit = set(12, value)
        get(): Long? = get(12) as Long?

    open override var enabled: Boolean?
        set(value): Unit = set(13, value)
        get(): Boolean? = get(13) as Boolean?

    open override var deleted: Boolean?
        set(value): Unit = set(14, value)
        get(): Boolean? = get(14) as Boolean?

    @get:NotNull
    open override var createBy: Long
        set(value): Unit = set(15, value)
        get(): Long = get(15) as Long

    open override var createTime: LocalDateTime?
        set(value): Unit = set(16, value)
        get(): LocalDateTime? = get(16) as LocalDateTime?

    open override var updateBy: Long?
        set(value): Unit = set(17, value)
        get(): Long? = get(17) as Long?

    open override var updateTime: LocalDateTime?
        set(value): Unit = set(18, value)
        get(): LocalDateTime? = get(18) as LocalDateTime?

    @get:NotNull
    open override var tenantId: Long
        set(value): Unit = set(19, value)
        get(): Long = get(19) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ITMenu) {
        this.menuId = from.menuId
        this.menuName = from.menuName
        this.path = from.path
        this.component = from.component
        this.level = from.level
        this.title = from.title
        this.icon = from.icon
        this.auth = from.auth
        this.keepAlive = from.keepAlive
        this.displayOrder = from.displayOrder
        this.menuType = from.menuType
        this.link = from.link
        this.upperMenuId = from.upperMenuId
        this.enabled = from.enabled
        this.deleted = from.deleted
        this.createBy = from.createBy
        this.createTime = from.createTime
        this.updateBy = from.updateBy
        this.updateTime = from.updateTime
        this.tenantId = from.tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TMenuRecord
     */
    constructor(menuId: Long, menuName: String, path: String, component: String, level: String, title: String? = null, icon: String? = null, auth: Boolean? = null, keepAlive: Boolean? = null, displayOrder: Int? = null, menuType: String? = null, link: String? = null, upperMenuId: Long? = null, enabled: Boolean? = null, deleted: Boolean? = null, createBy: Long, createTime: LocalDateTime? = null, updateBy: Long? = null, updateTime: LocalDateTime? = null, tenantId: Long): this() {
        this.menuId = menuId
        this.menuName = menuName
        this.path = path
        this.component = component
        this.level = level
        this.title = title
        this.icon = icon
        this.auth = auth
        this.keepAlive = keepAlive
        this.displayOrder = displayOrder
        this.menuType = menuType
        this.link = link
        this.upperMenuId = upperMenuId
        this.enabled = enabled
        this.deleted = deleted
        this.createBy = createBy
        this.createTime = createTime
        this.updateBy = updateBy
        this.updateTime = updateTime
        this.tenantId = tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TMenuRecord
     */
    constructor(value: ITMenu?): this() {
        if (value != null) {
            this.menuId = value.menuId
            this.menuName = value.menuName
            this.path = value.path
            this.component = value.component
            this.level = value.level
            this.title = value.title
            this.icon = value.icon
            this.auth = value.auth
            this.keepAlive = value.keepAlive
            this.displayOrder = value.displayOrder
            this.menuType = value.menuType
            this.link = value.link
            this.upperMenuId = value.upperMenuId
            this.enabled = value.enabled
            this.deleted = value.deleted
            this.createBy = value.createBy
            this.createTime = value.createTime
            this.updateBy = value.updateBy
            this.updateTime = value.updateTime
            this.tenantId = value.tenantId
            resetTouchedOnNotNull()
        }
    }
}
