/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.records


import cn.hubbo.dal.tables.TProjectIteration
import cn.hubbo.dal.tables.interfaces.ITProjectIteration

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 项目迭代记录表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TProjectIterationRecord private constructor() : UpdatableRecordImpl<TProjectIterationRecord>(TProjectIteration.T_PROJECT_ITERATION), ITProjectIteration {

    @get:NotNull
    open override var iterationId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    @get:NotNull
    open override var projectId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    @get:NotNull
    @get:Size(max = 255)
    open override var iterationName: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    @get:NotNull
    @get:Size(max = 64)
    open override var baseLine: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    @get:NotNull
    @get:Size(max = 64)
    open override var currentBranch: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open override var enabled: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open override var deleted: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    @get:NotNull
    open override var createBy: Long
        set(value): Unit = set(7, value)
        get(): Long = get(7) as Long

    open override var createTime: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open override var updateBy: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    open override var updateTime: LocalDateTime?
        set(value): Unit = set(10, value)
        get(): LocalDateTime? = get(10) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ITProjectIteration) {
        this.iterationId = from.iterationId
        this.projectId = from.projectId
        this.iterationName = from.iterationName
        this.baseLine = from.baseLine
        this.currentBranch = from.currentBranch
        this.enabled = from.enabled
        this.deleted = from.deleted
        this.createBy = from.createBy
        this.createTime = from.createTime
        this.updateBy = from.updateBy
        this.updateTime = from.updateTime
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TProjectIterationRecord
     */
    constructor(iterationId: Long, projectId: Long, iterationName: String, baseLine: String, currentBranch: String, enabled: Boolean? = null, deleted: Boolean? = null, createBy: Long, createTime: LocalDateTime? = null, updateBy: Long? = null, updateTime: LocalDateTime? = null): this() {
        this.iterationId = iterationId
        this.projectId = projectId
        this.iterationName = iterationName
        this.baseLine = baseLine
        this.currentBranch = currentBranch
        this.enabled = enabled
        this.deleted = deleted
        this.createBy = createBy
        this.createTime = createTime
        this.updateBy = updateBy
        this.updateTime = updateTime
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TProjectIterationRecord
     */
    constructor(value: ITProjectIteration?): this() {
        if (value != null) {
            this.iterationId = value.iterationId
            this.projectId = value.projectId
            this.iterationName = value.iterationName
            this.baseLine = value.baseLine
            this.currentBranch = value.currentBranch
            this.enabled = value.enabled
            this.deleted = value.deleted
            this.createBy = value.createBy
            this.createTime = value.createTime
            this.updateBy = value.updateBy
            this.updateTime = value.updateTime
            resetTouchedOnNotNull()
        }
    }
}
