/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.records


import cn.hubbo.dal.tables.TProject
import cn.hubbo.dal.tables.interfaces.ITProject

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import javax.annotation.processing.Generated

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 项目信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TProjectRecord private constructor() : UpdatableRecordImpl<TProjectRecord>(TProject.T_PROJECT), ITProject {

    @get:NotNull
    open override var projectId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    @get:NotNull
    @get:Size(max = 255)
    open override var projectName: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    @get:NotNull
    open override var projectOwner: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    @get:NotNull
    @get:Size(max = 255)
    open override var repositoryUrl: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    @get:NotNull
    @get:Size(max = 255)
    open override var masterBranch: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    @get:NotNull
    @get:Size(max = 1)
    open override var buildType: String
        set(value): Unit = set(5, value)
        get(): String = get(5) as String

    @get:NotNull
    open override var buildConfigId: Long
        set(value): Unit = set(6, value)
        get(): Long = get(6) as Long

    @get:NotNull
    @get:Size(max = 255)
    open override var currentBranch: String
        set(value): Unit = set(7, value)
        get(): String = get(7) as String

    @get:NotNull
    @get:Size(max = 1)
    open override var publishMode: String
        set(value): Unit = set(8, value)
        get(): String = get(8) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ITProject) {
        this.projectId = from.projectId
        this.projectName = from.projectName
        this.projectOwner = from.projectOwner
        this.repositoryUrl = from.repositoryUrl
        this.masterBranch = from.masterBranch
        this.buildType = from.buildType
        this.buildConfigId = from.buildConfigId
        this.currentBranch = from.currentBranch
        this.publishMode = from.publishMode
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TProjectRecord
     */
    constructor(projectId: Long, projectName: String, projectOwner: Long, repositoryUrl: String, masterBranch: String, buildType: String, buildConfigId: Long, currentBranch: String, publishMode: String): this() {
        this.projectId = projectId
        this.projectName = projectName
        this.projectOwner = projectOwner
        this.repositoryUrl = repositoryUrl
        this.masterBranch = masterBranch
        this.buildType = buildType
        this.buildConfigId = buildConfigId
        this.currentBranch = currentBranch
        this.publishMode = publishMode
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TProjectRecord
     */
    constructor(value: ITProject?): this() {
        if (value != null) {
            this.projectId = value.projectId
            this.projectName = value.projectName
            this.projectOwner = value.projectOwner
            this.repositoryUrl = value.repositoryUrl
            this.masterBranch = value.masterBranch
            this.buildType = value.buildType
            this.buildConfigId = value.buildConfigId
            this.currentBranch = value.currentBranch
            this.publishMode = value.publishMode
            resetTouchedOnNotNull()
        }
    }
}
