/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.records


import cn.hubbo.dal.tables.TRolePermission
import cn.hubbo.dal.tables.interfaces.ITRolePermission

import jakarta.validation.constraints.NotNull

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 角色权限关联信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TRolePermissionRecord private constructor() : UpdatableRecordImpl<TRolePermissionRecord>(TRolePermission.T_ROLE_PERMISSION), ITRolePermission {

    @get:NotNull
    open override var id: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    @get:NotNull
    open override var roleId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    @get:NotNull
    open override var permissionId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var enabled: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    @get:NotNull
    open override var createBy: Long
        set(value): Unit = set(4, value)
        get(): Long = get(4) as Long

    open override var createTime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open override var updateBy: Long?
        set(value): Unit = set(6, value)
        get(): Long? = get(6) as Long?

    open override var updateTime: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    @get:NotNull
    open override var tenantId: Long
        set(value): Unit = set(8, value)
        get(): Long = get(8) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ITRolePermission) {
        this.id = from.id
        this.roleId = from.roleId
        this.permissionId = from.permissionId
        this.enabled = from.enabled
        this.createBy = from.createBy
        this.createTime = from.createTime
        this.updateBy = from.updateBy
        this.updateTime = from.updateTime
        this.tenantId = from.tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TRolePermissionRecord
     */
    constructor(id: Long, roleId: Long, permissionId: Long, enabled: Boolean? = null, createBy: Long, createTime: LocalDateTime? = null, updateBy: Long? = null, updateTime: LocalDateTime? = null, tenantId: Long): this() {
        this.id = id
        this.roleId = roleId
        this.permissionId = permissionId
        this.enabled = enabled
        this.createBy = createBy
        this.createTime = createTime
        this.updateBy = updateBy
        this.updateTime = updateTime
        this.tenantId = tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TRolePermissionRecord
     */
    constructor(value: ITRolePermission?): this() {
        if (value != null) {
            this.id = value.id
            this.roleId = value.roleId
            this.permissionId = value.permissionId
            this.enabled = value.enabled
            this.createBy = value.createBy
            this.createTime = value.createTime
            this.updateBy = value.updateBy
            this.updateTime = value.updateTime
            this.tenantId = value.tenantId
            resetTouchedOnNotNull()
        }
    }
}
