/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.records


import cn.hubbo.dal.tables.TRole
import cn.hubbo.dal.tables.interfaces.ITRole

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.time.LocalDateTime

import javax.annotation.processing.Generated

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 角色基础信息表
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class TRoleRecord private constructor() : UpdatableRecordImpl<TRoleRecord>(TRole.T_ROLE), ITRole {

    @get:NotNull
    open override var roleId: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    @get:NotNull
    @get:Size(max = 255)
    open override var roleName: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open override var enabled: Boolean?
        set(value): Unit = set(2, value)
        get(): Boolean? = get(2) as Boolean?

    open override var deleted: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    @get:NotNull
    open override var createBy: Long
        set(value): Unit = set(4, value)
        get(): Long = get(4) as Long

    open override var createTime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open override var updateBy: Long?
        set(value): Unit = set(6, value)
        get(): Long? = get(6) as Long?

    open override var updateTime: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    @get:NotNull
    open override var tenantId: Long
        set(value): Unit = set(8, value)
        get(): Long = get(8) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ITRole) {
        this.roleId = from.roleId
        this.roleName = from.roleName
        this.enabled = from.enabled
        this.deleted = from.deleted
        this.createBy = from.createBy
        this.createTime = from.createTime
        this.updateBy = from.updateBy
        this.updateTime = from.updateTime
        this.tenantId = from.tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TRoleRecord
     */
    constructor(roleId: Long, roleName: String, enabled: Boolean? = null, deleted: Boolean? = null, createBy: Long, createTime: LocalDateTime? = null, updateBy: Long? = null, updateTime: LocalDateTime? = null, tenantId: Long): this() {
        this.roleId = roleId
        this.roleName = roleName
        this.enabled = enabled
        this.deleted = deleted
        this.createBy = createBy
        this.createTime = createTime
        this.updateBy = updateBy
        this.updateTime = updateTime
        this.tenantId = tenantId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised TRoleRecord
     */
    constructor(value: ITRole?): this() {
        if (value != null) {
            this.roleId = value.roleId
            this.roleName = value.roleName
            this.enabled = value.enabled
            this.deleted = value.deleted
            this.createBy = value.createBy
            this.createTime = value.createTime
            this.updateBy = value.updateBy
            this.updateTime = value.updateTime
            this.tenantId = value.tenantId
            resetTouchedOnNotNull()
        }
    }
}
