@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.keys


import cn.hubbo.dal.tables.TButtonPermission
import cn.hubbo.dal.tables.TDictData
import cn.hubbo.dal.tables.TMenu
import cn.hubbo.dal.tables.TMenuPermission
import cn.hubbo.dal.tables.TPermission
import cn.hubbo.dal.tables.TRole
import cn.hubbo.dal.tables.TRolePermission
import cn.hubbo.dal.tables.TUser
import cn.hubbo.dal.tables.TUserRole
import cn.hubbo.dal.tables.records.TButtonPermissionRecord
import cn.hubbo.dal.tables.records.TDictDataRecord
import cn.hubbo.dal.tables.records.TMenuPermissionRecord
import cn.hubbo.dal.tables.records.TMenuRecord
import cn.hubbo.dal.tables.records.TPermissionRecord
import cn.hubbo.dal.tables.records.TRolePermissionRecord
import cn.hubbo.dal.tables.records.TRoleRecord
import cn.hubbo.dal.tables.records.TUserRecord
import cn.hubbo.dal.tables.records.TUserRoleRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val T_BUTTON_PERMISSION_BUTTON_PERMISSION_CODE_KEY: UniqueKey<TButtonPermissionRecord> = Internal.createUniqueKey(TButtonPermission.T_BUTTON_PERMISSION, DSL.name("t_button_permission_button_permission_code_key"), arrayOf(TButtonPermission.T_BUTTON_PERMISSION.BUTTON_PERMISSION_CODE), true)
val T_BUTTON_PERMISSION_PK: UniqueKey<TButtonPermissionRecord> = Internal.createUniqueKey(TButtonPermission.T_BUTTON_PERMISSION, DSL.name("t_button_permission_pk"), arrayOf(TButtonPermission.T_BUTTON_PERMISSION.ID), true)
val T_DICT_DATA_PK: UniqueKey<TDictDataRecord> = Internal.createUniqueKey(TDictData.T_DICT_DATA, DSL.name("t_dict_data_pk"), arrayOf(TDictData.T_DICT_DATA.DICT_ID), true)
val T_MENU_PK: UniqueKey<TMenuRecord> = Internal.createUniqueKey(TMenu.T_MENU, DSL.name("t_menu_pk"), arrayOf(TMenu.T_MENU.MENU_ID), true)
val T_MENU_PERMISSION_PK: UniqueKey<TMenuPermissionRecord> = Internal.createUniqueKey(TMenuPermission.T_MENU_PERMISSION, DSL.name("t_menu_permission_pk"), arrayOf(TMenuPermission.T_MENU_PERMISSION.ID), true)
val T_PERMISSION_PERMISSION_CODE_KEY: UniqueKey<TPermissionRecord> = Internal.createUniqueKey(TPermission.T_PERMISSION, DSL.name("t_permission_permission_code_key"), arrayOf(TPermission.T_PERMISSION.PERMISSION_CODE), true)
val T_PERMISSION_PK: UniqueKey<TPermissionRecord> = Internal.createUniqueKey(TPermission.T_PERMISSION, DSL.name("t_permission_pk"), arrayOf(TPermission.T_PERMISSION.PERMISSION_ID), true)
val T_ROLE_PK: UniqueKey<TRoleRecord> = Internal.createUniqueKey(TRole.T_ROLE, DSL.name("t_role_pk"), arrayOf(TRole.T_ROLE.ROLE_ID), true)
val T_ROLE_PERMISSION_PK: UniqueKey<TRolePermissionRecord> = Internal.createUniqueKey(TRolePermission.T_ROLE_PERMISSION, DSL.name("t_role_permission_pk"), arrayOf(TRolePermission.T_ROLE_PERMISSION.ID), true)
val T_ROLE_PERMISSION_UK: UniqueKey<TRolePermissionRecord> = Internal.createUniqueKey(TRolePermission.T_ROLE_PERMISSION, DSL.name("t_role_permission_uk"), arrayOf(TRolePermission.T_ROLE_PERMISSION.ROLE_ID, TRolePermission.T_ROLE_PERMISSION.PERMISSION_ID, TRolePermission.T_ROLE_PERMISSION.ENABLED), true)
val T_USER_PHONE_KEY: UniqueKey<TUserRecord> = Internal.createUniqueKey(TUser.T_USER, DSL.name("t_user_phone_key"), arrayOf(TUser.T_USER.PHONE), true)
val T_USER_PK: UniqueKey<TUserRecord> = Internal.createUniqueKey(TUser.T_USER, DSL.name("t_user_pk"), arrayOf(TUser.T_USER.USER_ID), true)
val T_USER_ROLE_PK: UniqueKey<TUserRoleRecord> = Internal.createUniqueKey(TUserRole.T_USER_ROLE, DSL.name("t_user_role_pk"), arrayOf(TUserRole.T_USER_ROLE.ID), true)
