@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal.tables.references


import cn.hubbo.dal.tables.TDictData
import cn.hubbo.dal.tables.TMenu
import cn.hubbo.dal.tables.TMenuPermission
import cn.hubbo.dal.tables.TPermission
import cn.hubbo.dal.tables.TRole
import cn.hubbo.dal.tables.TRolePermission
import cn.hubbo.dal.tables.TUser
import cn.hubbo.dal.tables.TUserRole



/**
 * 字典表
 */
val T_DICT_DATA: TDictData = TDictData.T_DICT_DATA

/**
 * 菜单配置信息表，对应前端的路由信息
 */
val T_MENU: TMenu = TMenu.T_MENU

/**
 * 菜单权限关联表
 */
val T_MENU_PERMISSION: TMenuPermission = TMenuPermission.T_MENU_PERMISSION

/**
 * 权限信息表
 */
val T_PERMISSION: TPermission = TPermission.T_PERMISSION

/**
 * 角色基础信息表
 */
val T_ROLE: TRole = TRole.T_ROLE

/**
 * 角色权限关联信息表
 */
val T_ROLE_PERMISSION: TRolePermission = TRolePermission.T_ROLE_PERMISSION

/**
 * 用户基础信息表
 */
val T_USER: TUser = TUser.T_USER

/**
 * 用户角色关联信息表
 */
val T_USER_ROLE: TUserRole = TUserRole.T_USER_ROLE
