/*
 * This file is generated by jOOQ.
 */
package cn.hubbo.dal


import cn.hubbo.dal.tables.TButtonPermission
import cn.hubbo.dal.tables.TDictData
import cn.hubbo.dal.tables.TMenu
import cn.hubbo.dal.tables.TMenuPermission
import cn.hubbo.dal.tables.TPermission
import cn.hubbo.dal.tables.TRole
import cn.hubbo.dal.tables.TRolePermission
import cn.hubbo.dal.tables.TUser
import cn.hubbo.dal.tables.TUserRole

import javax.annotation.processing.Generated

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    ],
    comments = "This class is generated by jOOQ"
)
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * 按钮权限关联信息表
     */
    val T_BUTTON_PERMISSION: TButtonPermission get() = TButtonPermission.T_BUTTON_PERMISSION

    /**
     * 字典表
     */
    val T_DICT_DATA: TDictData get() = TDictData.T_DICT_DATA

    /**
     * 菜单配置信息表，对应前端的路由信息
     */
    val T_MENU: TMenu get() = TMenu.T_MENU

    /**
     * 菜单权限关联表
     */
    val T_MENU_PERMISSION: TMenuPermission get() = TMenuPermission.T_MENU_PERMISSION

    /**
     * 权限信息表
     */
    val T_PERMISSION: TPermission get() = TPermission.T_PERMISSION

    /**
     * 角色基础信息表
     */
    val T_ROLE: TRole get() = TRole.T_ROLE

    /**
     * 角色权限关联信息表
     */
    val T_ROLE_PERMISSION: TRolePermission get() = TRolePermission.T_ROLE_PERMISSION

    /**
     * 用户基础信息表
     */
    val T_USER: TUser get() = TUser.T_USER

    /**
     * 用户角色关联信息表
     */
    val T_USER_ROLE: TUserRole get() = TUserRole.T_USER_ROLE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        TButtonPermission.T_BUTTON_PERMISSION,
        TDictData.T_DICT_DATA,
        TMenu.T_MENU,
        TMenuPermission.T_MENU_PERMISSION,
        TPermission.T_PERMISSION,
        TRole.T_ROLE,
        TRolePermission.T_ROLE_PERMISSION,
        TUser.T_USER,
        TUserRole.T_USER_ROLE
    )
}
