# 新版本的rocketmq5基于grpc调用
rocketmq:
  producer:
    endpoints: ${rocketmq.host}:${rocketmq.port}
    topic: ${rocketmq.producers.topic}
    ssl-enabled: ${rocketmq.ssl.enabled}
  simple-consumer:
    endpoints: ${rocketmq.host}:${rocketmq.port}
    consumer-group: ${rocketmq.consumers.group}
    topic: ${rocketmq.consumer.topic}
    tag: ${rocketmq.consumer.tag}


