r2dbc:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.dbname}?directConnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    host: ${db.host}
    port: ${db.port}
    dbname: ${db.dbname}
    username: ${db.username}
    password: ${db.passwd}
    driver: ${db.driver}


spring:
  data:
    redis:
      host: ${redis.host:127.0.0.1}
      port: ${redis.port:6379}
      password: ${redis.password}
      database: ${redis.database:0}
