r2dbc:
  datasource:
    # 供 jOOQ 代码生成等场景使用的 JDBC URL
    url: jdbc:postgresql://${db.host}:${db.port}/${db.dbname}?directConnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    host: ${db.host}
    port: ${db.port}
    dbname: ${db.dbname}
    username: ${db.username}
    password: ${db.passwd}
    driver: ${db.driver}
    pool-max-size: 10
    pool-max-idle-time-seconds: 60


spring:
  data:
    redis:
      host: ${redis.host:127.0.0.1}
      port: ${redis.port:6379}
      password: ${redis.password}
      database: ${redis.database:0}
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 3
          max-wait: 3000
          min-idle: 1