package cn.hubbo.utils.coding

import javax.lang.model.element.Modifier
import javax.lang.model.type.TypeMirror

/**
 * todo 支持specify的注解 对函数入参进行非空校验
 */

private const val SUBCLASS_PREFIX = "Impl"
private const val GENERATED_COMMENT = "Generated By Hubbo-native-binding"

data class JavaSourceStructureInfo(

    /**
     * 修饰符
     */
    val modifiers: Set<Modifier>,

    /**
     * 类名
     */
    val className: String,

    /**
     * 父类
     */
    val supperClass: TypeMirror,

    /**
     * 函数声明
     */
    val methodDeclarations: List<MethodDeclaration>?
) {

    /**
     * 包名
     */
    lateinit var packageName: String

    /**
     * 注释
     */
    var comment: String = GENERATED_COMMENT


    /**
     * 子类名
     */
    fun subClassName(): String {
        if (::packageName.isInitialized) {
            return "$className$SUBCLASS_PREFIX"
        }
        return className
    }

    fun getFullQualifiedName(): String {
        return "$packageName.$className"
    }


}
